// <auto-generated />
using System;
using ChatApp.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChatApp.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ChatApp.Core.Models.Chat", b =>
            {
                b.Property<Guid>("Id").HasColumnType("TEXT");
                b.Property<string>("Type").HasColumnType("TEXT");
                b.Property<string>("Name").HasColumnType("TEXT");
                b.Property<string>("AvatarUrl").HasColumnType("TEXT");
                b.Property<string>("Description").HasColumnType("TEXT");
                b.Property<string>("InviteToken").HasColumnType("TEXT");
                b.Property<bool>("IsPublic").HasColumnType("INTEGER");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("Chats");
            });

            modelBuilder.Entity("ChatApp.Core.Models.User", b =>
            {
                b.Property<Guid>("Id").HasColumnType("TEXT");
                b.Property<string>("Username").HasColumnType("TEXT");
                b.Property<string>("DisplayName").HasColumnType("TEXT");
                b.Property<string>("PasswordHash").HasColumnType("TEXT");
                b.Property<string>("AvatarUrl").HasColumnType("TEXT");
                b.Property<string>("Bio").HasColumnType("TEXT");
                b.Property<DateTime>("LastSeen").HasColumnType("TEXT");
                b.Property<bool>("IsOnline").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.HasIndex("Username").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("ChatApp.Core.Models.ChatMember", b =>
            {
                b.Property<Guid>("ChatId").HasColumnType("TEXT");
                b.Property<Guid>("UserId").HasColumnType("TEXT");
                b.Property<string>("Role").HasColumnType("TEXT");
                b.Property<DateTime>("JoinedAt").HasColumnType("TEXT");
                b.Property<DateTime?>("LastReadAt").HasColumnType("TEXT");
                b.Property<bool>("IsMuted").HasColumnType("INTEGER");
                b.HasKey("ChatId", "UserId");
                b.ToTable("ChatMembers");
            });

            modelBuilder.Entity("ChatApp.Core.Models.Message", b =>
            {
                b.Property<Guid>("Id").HasColumnType("TEXT");
                b.Property<Guid>("ChatId").HasColumnType("TEXT");
                b.Property<Guid>("SenderId").HasColumnType("TEXT");
                b.Property<string>("Content").HasColumnType("TEXT");
                b.Property<string>("Type").HasColumnType("TEXT");
                b.Property<Guid?>("ReplyToId").HasColumnType("TEXT");
                b.Property<bool>("IsEdited").HasColumnType("INTEGER");
                b.Property<bool>("IsDeleted").HasColumnType("INTEGER");
                b.Property<bool>("IsPinned").HasColumnType("INTEGER");
                b.Property<DateTime>("SentAt").HasColumnType("TEXT");
                b.Property<DateTime?>("EditedAt").HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("Messages");
            });

            modelBuilder.Entity("ChatApp.Core.Models.MessageAttachment", b =>
            {
                b.Property<Guid>("Id").HasColumnType("TEXT");
                b.Property<Guid>("MessageId").HasColumnType("TEXT");
                b.Property<string>("Url").HasColumnType("TEXT");
                b.Property<string>("FileName").HasColumnType("TEXT");
                b.Property<long>("FileSize").HasColumnType("INTEGER");
                b.Property<string>("MimeType").HasColumnType("TEXT");
                b.Property<int?>("Width").HasColumnType("INTEGER");
                b.Property<int?>("Height").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.ToTable("MessageAttachments");
            });

            modelBuilder.Entity("ChatApp.Core.Models.MessageReaction", b =>
            {
                b.Property<Guid>("MessageId").HasColumnType("TEXT");
                b.Property<Guid>("UserId").HasColumnType("TEXT");
                b.Property<string>("Emoji").HasColumnType("TEXT");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.HasKey("MessageId", "UserId");
                b.ToTable("MessageReactions");
            });

            modelBuilder.Entity("ChatApp.Core.Models.Status", b =>
            {
                b.Property<Guid>("Id").HasColumnType("TEXT");
                b.Property<Guid>("UserId").HasColumnType("TEXT");
                b.Property<string>("Content").HasColumnType("TEXT");
                b.Property<string>("MediaUrl").HasColumnType("TEXT");
                b.Property<string>("MediaType").HasColumnType("TEXT");
                b.Property<string>("BackgroundColor").HasColumnType("TEXT");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<DateTime>("ExpiresAt").HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("Statuses");
            });

            modelBuilder.Entity("ChatApp.Core.Models.StatusView", b =>
            {
                b.Property<Guid>("StatusId").HasColumnType("TEXT");
                b.Property<Guid>("ViewerId").HasColumnType("TEXT");
                b.Property<DateTime>("ViewedAt").HasColumnType("TEXT");
                b.HasKey("StatusId", "ViewerId");
                b.ToTable("StatusViews");
            });
#pragma warning restore 612, 618
        }
    }
}
